### ISSUE TITLE
error : unterminated entity reference  Replication Server

### ISSUE THREAD

**Issue by archenroot** [kakwa/libvisio2svg#13] opened 2017-03-03 14:54 UTC
While trying to convert 2d and 3d stencils for virtual environments from:
https://www.veeam.com/vmware-esx-stencils-download.html#

I experienced:
```
zangetsu@ares ~/Downloads/Stencils $ /usr/bin/vss2svg-conv --input=2d_stencils_2010.vss --output=/home/zangetsu/Downloads/Stencils/virtual2d
error : unterminated entity reference  Replication Server
```

**Comment by kakwa** [comment] 2017-03-05 00:46
It was caused by the "&" in "Veeam Backup & Replication Server"

However the only consequence was an empty title.

It's fixed by https://github.com/kakwa/libvisio2svg/commit/2ab359b56cfefcc36fedd4bd328defcf1f3569db

(Putting the titles inside cdata[[ ]])

Once again, most of the SVGs generated are empty, and libvisio/librevenge gives weird coordinates.

**Comment by archenroot** [comment] 2017-03-05 11:42
Hm, thanks for this quick fix and lets open another issue with empty SVGs. I will first test tomorrow on my linux box.

**Closed** 2017-11-30 07:29 UTC
