### ISSUE TITLE
Service Inventory:74: parser error : internal error: Huge input lookup

### ISSUE THREAD

**Issue by archenroot** [kakwa/libvisio2svg#12] opened 2017-03-03 14:34 UTC
While trying to convert following Stencil:
http://arcitura.com/system/application/visio/CCP_Visio_Stencil.zip

I experienced:
```
zangetsu@ares ~/Downloads/Stencils $ /usr/bin/vss2svg-conv --input=CCP_Visio_Stencil.vss --output=/home/zangetsu/Downloads/Stencils/big-data
Service Inventory:74: parser error : internal error: Huge input lookup
AAAAAAgD8AAAAAAAAAAAAAgD8AAAAAAAAAACIAAAAMAAAA/////w4AAAAUAAAAAAAAABAAAAAUAAAA" 
```
                                                                               ^

**Comment by archenroot** [comment] 2017-03-03 14:37
Same issue:
```
zangetsu@ares ~/Downloads/Stencils $ /usr/bin/vss2svg-conv --input=SOACP_Visio_Stencil.vss --output=/home/zangetsu/Downloads/Stencils/soacp
Service Inventory:74: parser error : internal error: Huge input lookup
AAAAAAgD8AAAAAAAAAAAAAgD8AAAAAAAAAACIAAAAMAAAA/////w4AAAAUAAAAAAAAABAAAAAUAAAA" 
                                                                               ^

```

File to download http://www.arcitura.com/notation

**Comment by kakwa** [comment] 2017-03-03 16:57
It seems related:

http://stackoverflow.com/questions/24531634/libxml2-xml-parse-huge-option-for-xmlparsememory

**Comment by kakwa** [comment] 2017-03-04 20:43
The error is fixed by:

https://github.com/kakwa/libvisio2svg/commit/206765f610bd5078c76fe7761750fd9223d7de5a

However, with the CCP stencils you point, the result is "empty" SVGs.

In fact the SVGs are not empty, libvisio/librevenge places most of the content outside the image (ex with "Actively Processing", the content is positioned at x="3456.0000" y="-756.0000", with an image with dimensions of width="38.6615" height="38.7120" it's rather strange...).

vss2xhtml (the tool from libvisio, which generate SVG to, without handling emf/wmf blobs) gives the same weird values.

**Comment by archenroot** [comment] 2017-03-05 11:55
Thanks for fix. I will look into this tomorrow in more detail. I don't know these libraries much so probably, but understand in general what is wrong here. Thanks for explanation.
Well actually these stencils are core of my design toolset, so lets try to realize where the root cause lies.

**Comment by kakwa** [comment] 2017-03-05 20:34
There is not a lot of things I could do except opening a bug in libvisio bugzilla.

This project is only a glue between:
* libvisio & librevenge
* libwmf
* libemf2svg (which I maintain to)

**Comment by kakwa** [comment] 2017-03-05 21:30
I've opened a ticket there:

https://bugs.documentfoundation.org/show_bug.cgi?id=106344

**Comment by kakwa** [comment] 2017-03-05 21:40
Otherwise, even if it's not the most practical thing to do, you can rework the generated SVG in inkscape or directly by editing directly the SVG file.

**Comment by archenroot** [comment] 2017-03-06 08:47
I see :-), so in minimum we have workaround.

Thanks for the bug opened.

**Comment by archenroot** [comment] 2017-03-21 12:38
Hi buddy, could you please provide more information on the upstream bug opened?

**Comment by kakwa** [comment] 2017-03-21 20:04
Hi, sorry for the delay, I've uploaded the screeshots to upstream

**Comment by archenroot** [comment] 2017-06-05 09:17
@kakwa - not big deal, the problem is mainly with upstream... lets see if they will ever fix this...

Thanks a lot for support.

**Comment by kakwa** [comment] 2018-11-28 13:18
Closing it as it's now a duplicate of https://github.com/kakwa/libvisio2svg/issues/15

**Closed by kakwa** 2018-11-28 13:18 UTC
